text_triangle: triangle.c geometry.c geometry.h text.c encoding.h
	gcc -Wall -std=c99 triangle.c geometry.c text.c -o text_triangle
binary_triangle: triangle.c geometry.c geometry.h binary.c encoding.h
	gcc -Wall -std=c99 triangle.c geometry.c binary.c -o binary_triangle
